export const SET_AVAILABLE_FLIGHTS = "SET_AVAILABLE_FLIGHTS";
export const FLIGHT_SELECTED = "FLIGHT_SELECTED";
export const SET_FILTER = "ticketBoard/SET_FILTER";
export const ON_AIRCOMPANY_SELECT = "ON_AIRCOMPANY_SELECT";